cmake_minimum_required(VERSION 3.16)
project(at_nav2)

find_package(ament_cmake REQUIRED)
find_package(cartographer_ros REQUIRED)
find_package(nav2_bringup REQUIRED)
find_package(nav2_planner REQUIRED)
find_package(nav2_controller REQUIRED)
find_package(nav2_costmap_2d REQUIRED)

set(_install_dirs "")

foreach(dir launch config maps)
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${dir}")
    list(APPEND _install_dirs "${dir}")
  endif()
endforeach()

if(_install_dirs)
  install(DIRECTORY
    ${_install_dirs}
    DESTINATION share/${PROJECT_NAME}/
  )
endif()

ament_package()
